apiVersion: v1
kind: Service
metadata:
  labels:
    app: notificationicroservice
  name: notification-service
spec:
  ports:
  - protocol: TCP
    port: 8083
    targetPort: 8083
  selector:
    app: notificationmicroservice
  type: LoadBalancer
status:
  loadBalancer: {}
