apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: notificationmicroservice
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: notificationmicroservice
    spec:
      containers:
      - image: d3334/notificationms:8
        name: notificationmicroservice
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
        imagePullPolicy: Always
        ports:
        - name: notification-port
          containerPort: 8083
status: {}
